name: "build-binaries"

on:
  push:
    branches:
      - "master"

jobs:
  windows-build:
    name: "Windows Build"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y virtualenv
          pip install virtualenv
          python -m virtualenv .venv
          .venv\scripts\activate
          pip install -r requirements.txt

      - name: "Package Build"
        run: |
          python -m pip install pyinstaller
          python build.py -e

      - name: "Peek Directory"
        run: |
          echo %cd%
          dir > peek.txt
          more peek.txt

  macOS-build:
    name: "MacOS Build"
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v3

    - name: "Setup Python 3.9"
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: "Install Dependencies"
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y virtualenv
        pip install virtualenv
        python -m virtualenv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: "Package Build"
      run: |
        python -m pip install pyinstaller
        python build.py -e

  zip-windows-binary:
    needs: windows-build
    name: "Zip Windows Binary"
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r emailtracker_win.zip . -i dist

      - name: "Peek Directory"
        run: |
          cd ./dist
          echo %cd%
          dir > peek.txt
          more peek.txt

  zip-macos-binary:
    needs: macOS-build
    name: "Zip MacOS Binary"
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r emailtracker_mac.zip . -i dist

  release:
    needs: [zip-windows-binary, zip-macos-binary]
    runs-on: ubuntu-latest
    steps:
      - name: "release"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest development build"
          files: |
            emailtracker_Win.zip
            emailtracker_Mac.zip




